version: '3.8'

services:
  # Base de datos para desarrollo
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: menuhub_dev
      POSTGRES_USER: menuhub
      POSTGRES_PASSWORD: menuhub123
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # Límites ligeros para desarrollo
    mem_limit: 256m
    memswap_limit: 256m
    cpus: 0.5

  # Backend en modo desarrollo
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: "postgresql://menuhub:menuhub123@database:5432/menuhub_dev"
      JWT_SECRET: "supersecreto_desarrollo"
      NODE_ENV: development
      # En desarrollo no definimos CORS_ORIGINS para ser más permisivo
    ports:
      - "3000:3000"
    # Límites para desarrollo con hot reload
    mem_limit: 512m
    memswap_limit: 512m
    cpus: 1.5
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - database
    command: npm run dev

  # Frontend en modo desarrollo
  frontend:
    build:
      context: ../menu-hub-frontend/menu-hub
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    # Límites para Vite dev server
    mem_limit: 512m
    memswap_limit: 512m
    cpus: 1.0
    volumes:
      - ../menu-hub-frontend/menu-hub:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:3000

volumes:
  postgres_dev_data:
    driver: local
